<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 11" />
<title>MeshMeshIntersection</title>

 <link rel="StyleSheet" href="../../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../../whmsg.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript" src="../../whver.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whutils.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whproxy.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whlang.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whtopic.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	addTocInfo("Modules\nmesh\nmeshmeshintersection");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../../whd_show0.gif","../../whd_show2.gif","../../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../../whd_hide0.gif","../../whd_hide2.gif","../../whd_hide1.gif");
addButton("prev",BTN_IMG,"<<","","","","",0,0,"../../whd_prev0.gif","../../whd_prev2.gif","../../whd_prev1.gif");
addButton("next",BTN_IMG,">>","","","","",0,0,"../../whd_next0.gif","../../whd_next2.gif","../../whd_next1.gif");


	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../../index.html", "", ">", "Home", "../../title.htm");
document.write("<a href=\"../../introduction/rhino_package.htm\">Modules<\/a> > <a href=\"mesh_module.htm\">mesh<\/a> > meshmeshintersection<\/p>");

}
else
	if (window.gbIE4)
		document.location.reload();
    
onLoadHandler = function()
{
	if (window.setRelStartPage)
	{
    setTimeout("setRelStartPage('../../index.html');", 1)

    setTimeout("UpdateBreadCrumbsMarker();", 1);
    }
} 

if (window.addEventListener){  
	window.addEventListener('load', onLoadHandler, false);   
} else if (window.attachEvent){  
	window.attachEvent('onload', onLoadHandler);  
}

function onSetStartPage()
{
	autoSync(1);
	sendSyncInfo();
	sendAveInfoOut();
}
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<script type="text/javascript" src="../../ehlpdhtm.js" language="JavaScript1.2"></script>

<h1>MeshMeshIntersection</h1>
<p>Calculates the intersection of a mesh object with another mesh object.</p>
<h3>Syntax</h3>
<p class="Code">rhinoscriptsyntax.MeshMeshIntersection (mesh1, mesh2, tolerance=None)</p>
<p class="Code">rhinoscript.mesh.MeshMeshIntersection (mesh1, mesh2, tolerance=None)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.408%;" />
<col style="width: 90.592%;" />
<tr style="vertical-align: top;">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">mesh1</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String or Guid. &#160;The identifier of the first mesh object.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">mesh2</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String or Guid. &#160;The identifier of the second mesh object.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">tolerance</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Number. &#160;The intersection tolerance. Of omitted, Rhino's internal zero tolerance is used.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.53%;" />
<col style="width: 90.47%;" />
<tr style="vertical-align: top;">
<td style="width: 9.53%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">List</p>
</td>
<td style="width: 90.47%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">A list of 3-D point arrays that identify the vertices of the intersection curves (polylines) if successful.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td style="width: 9.53%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">None</p>
</td>
<td style="width: 90.47%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">import rhinoscriptsyntax as rs</p>
<p class="Code" style="margin-left: 12px;">mesh1 = rs.GetObject("Select first mesh to intersect", rs.filter.mesh)</p>
<p class="Code" style="margin-left: 12px;">mesh2 = rs.GetObject("Select second mesh to intersect", rs.filter.mesh)</p>
<p class="Code" style="margin-left: 12px;">results = rs.MeshMeshIntersection(mesh1, mesh2)</p>
<p class="Code" style="margin-left: 12px;">if results:</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;for points in results: rs.AddPolyline(points)</p>
<h3 class="Code">Also See</h3>
<p><a href="curvemeshintersection.htm">CurveMeshIntersection</a></p>
<p><a href="meshclosestpoint.htm">MeshClosestPoint</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
