---
---
<!-- HTML header for doxygen 1.8.9.1-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.9.1"/>
<title>rhinoscriptsyntax API docs: /Users/acormier/src/mcneel.com/RhinoDocsMainGhpSite/developer-rhino3d-com-externals/rhinoscriptsyntax/Scripts/rhinoscript/plane.py Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
  $(window).load(resizeHeight);
</script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<link href="customdoxygen.css" rel="stylesheet" type="text/css" />
<link href="customdoxygen-rhinodocs.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/github.min.css">
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/vbnet.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<!-- Overridden theme -->
<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<!-- Bootstrap override -->
<link rel="stylesheet" href="{{ "/css/bootstrap-override.css" | prepend: site.baseurl }}">
<link rel="canonical" href="{{ page.url | replace:'index.html','' | prepend: site.baseurl | prepend: site.url }}">
<link rel="alternate" type="application/rss+xml" title="{{ site.title }}" href="{{ "/feed.xml" | prepend: site.baseurl | prepend: site.url }}" />
<!-- Favicon -->
<link rel="icon" type="image/png" href="{{ site.baseurl }}/favicon.png">
</head>
<body>
  <header class="site-header">
    <a class="site-title" href="{{ site.baseurl }}/"><img src="{{ site.baseurl }}/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="{{ site.baseurl }}/">{{ site.title }}</a>
    <nav class="site-nav">
      {% assign pages = site.pages | sort:"order"  %}
      <div class="trigger">
      	<a class="page-link" href="{{ site.baseurl }}/">Welcome</a>
        {% for page in pages %}
          {% if page.title != 'TODO List' %}
            {% if page.title and page.order %}
            <a class="page-link" href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a>
            {% endif %}
          {% endif %}
        {% endfor %}
        <a class="page-link" href="http://discourse.mcneel.com/c/rhino-developer">Forums</a>
      </div>
    </nav>
</header>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td style="padding-left: 0.5em;">
   <div id="projectname">rhinoscriptsyntax API docs
   </div>
  </td>
   <td>        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
</td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.9.1 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(document).ready(function(){initNavTree('plane_8py_source.html','');});
</script>
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">plane.py</div>  </div>
</div><!--header-->
<div class="contents">
<div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno"><a class="line" href="namespacerhinoscript_1_1plane.html">    1</a></span>&#160;<span class="keyword">import</span> utility <span class="keyword">as</span> rhutil</div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="keyword">import</span> Rhino.Geometry</div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="keyword">import</span> scriptcontext</div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="keyword">import</span> math</div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;</div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="keyword">def </span>DistanceToPlane(plane, point):</div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;    <span class="stringliteral">&quot;Returns the distance from a 3D point to a plane&quot;</span></div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;    point = rhutil.coerce3dpoint(point, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;    <span class="keywordflow">return</span> plane.DistanceTo(point)</div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;</div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="keyword">def </span>EvaluatePlane(plane, parameter):</div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Evaluates a plane at a U,V parameter</span></div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="stringliteral">      plane = the plane to evaluate</span></div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="stringliteral">      parameter = list of two numbers defining the U,V parameter to evaluate</span></div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="stringliteral">      Point3d on success</span></div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;    <span class="keywordflow">return</span> plane.PointAt(parameter[0], parameter[1])</div>
<div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;</div>
<div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160;</div>
<div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;<span class="keyword">def </span>IntersectPlanes(plane1, plane2, plane3):</div>
<div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Calculates the intersection of three planes</span></div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;<span class="stringliteral">      Point3d on success</span></div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="stringliteral">      None on error</span></div>
<div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;    plane1 = rhutil.coerceplane(plane1, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;    plane2 = rhutil.coerceplane(plane2, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;    plane3 = rhutil.coerceplane(plane3, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;    rc, point = Rhino.Geometry.Intersect.Intersection.PlanePlanePlane(plane1, plane2, plane3)</div>
<div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;    <span class="keywordflow">if</span> rc: <span class="keywordflow">return</span> point</div>
<div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;</div>
<div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;</div>
<div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;<span class="keyword">def </span>MovePlane(plane, origin):</div>
<div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Moves the origin of a plane</span></div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;<span class="stringliteral">      plane = Plane or ConstructionPlane</span></div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="stringliteral">      origin = Point3d or list of three numbers</span></div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;<span class="stringliteral">      moved plane</span></div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;    origin = rhutil.coerce3dpoint(origin, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;    rc = Rhino.Geometry.Plane(plane)</div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;    rc.Origin = origin</div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;    <span class="keywordflow">return</span> rc</div>
<div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;</div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;</div>
<div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;<span class="keyword">def </span>PlaneClosestPoint(plane, point, return_point=True):</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Returns the point on a plane that is closest to a test point.</span></div>
<div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;<span class="stringliteral">      plane = The plane</span></div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="stringliteral">      point = The 3-D point to test.</span></div>
<div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;<span class="stringliteral">      return_point [opt] = If omitted or True, then the point on the plane</span></div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;<span class="stringliteral">         that is closest to the test point is returned. If False, then the</span></div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="stringliteral">         parameter of the point on the plane that is closest to the test</span></div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;<span class="stringliteral">         point is returned.</span></div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="stringliteral">      If return_point is omitted or True, then the 3-D point</span></div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;<span class="stringliteral">      If return_point is False, then an array containing the U,V parameters</span></div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;<span class="stringliteral">      of the point</span></div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;<span class="stringliteral">      None if not successful, or on error.</span></div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;    point = rhutil.coerce3dpoint(point, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;    <span class="keywordflow">if</span> return_point:</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        <span class="keywordflow">return</span> plane.ClosestPoint(point)</div>
<div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;    <span class="keywordflow">else</span>:</div>
<div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;        rc, s, t = plane.ClosestParameter(point)</div>
<div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;        <span class="keywordflow">if</span> rc: <span class="keywordflow">return</span> s, t</div>
<div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;</div>
<div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;<span class="keyword">def </span>PlaneCurveIntersection(plane, curve, tolerance=None):</div>
<div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    <span class="stringliteral">&quot;Intersect an infinite plane and a curve object&quot;</span></div>
<div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;    curve = rhutil.coercecurve(curve, -1, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;    <span class="keywordflow">if</span> tolerance <span class="keywordflow">is</span> <span class="keywordtype">None</span>: tolerance = scriptcontext.doc.ModelAbsoluteTolerance</div>
<div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;    intersections = Rhino.Geometry.Intersect.Intersection.CurvePlane(curve, plane, tolerance)</div>
<div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    <span class="keywordflow">if</span> intersections:</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        rc = []</div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;        <span class="keywordflow">for</span> intersection <span class="keywordflow">in</span> intersections:</div>
<div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;            a = 1</div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;            <span class="keywordflow">if</span> intersection.IsOverlap: a = 2</div>
<div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;            b = intersection.PointA</div>
<div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;            c = intersection.PointA2</div>
<div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;            d = intersection.PointB</div>
<div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;            e = intersection.PointB2</div>
<div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;            f = intersection.ParameterA</div>
<div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;            g = intersection.ParameterB</div>
<div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;            h = intersection.OverlapA[0]</div>
<div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;            i = intersection.OverlapA[1]</div>
<div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;            j = intersection.OverlapB[0]</div>
<div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;            k = intersection.OverlapB[1]</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;            rc.append( (a,b,c,d,e,f,g,h,i,j,k) )</div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;        <span class="keywordflow">return</span> rc</div>
<div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;</div>
<div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;</div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;<span class="keyword">def </span>PlaneEquation(plane):</div>
<div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Returns the equation of a plane as a tuple of four numbers. The standard</span></div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;<span class="stringliteral">    equation of a plane with a non-zero vector is Ax+By+Cz+D=0</span></div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;    rc = plane.GetPlaneEquation()</div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;    <span class="keywordflow">return</span> rc[0], rc[1], rc[2], rc[3]</div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;</div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;</div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;<span class="keyword">def </span>PlaneFitFromPoints(points):</div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Returns a plane that was fit through an array of 3D points.</span></div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;<span class="stringliteral">    points = An array of 3D points.</span></div>
<div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;<span class="stringliteral">    Returns: </span></div>
<div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;<span class="stringliteral">      The plane if successful</span></div>
<div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;<span class="stringliteral">      None if not successful</span></div>
<div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;    points = rhutil.coerce3dpointlist(points, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;    rc, plane = Rhino.Geometry.Plane.FitPlaneToPoints(points)</div>
<div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;    <span class="keywordflow">if</span> rc==Rhino.Geometry.PlaneFitResult.Success: <span class="keywordflow">return</span> plane</div>
<div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;</div>
<div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;</div>
<div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;<span class="keyword">def </span>PlaneFromFrame(origin, x_axis, y_axis):</div>
<div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Construct a plane from a point, and two vectors in the plane.</span></div>
<div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;<span class="stringliteral">      origin = A 3D point identifying the origin of the plane.</span></div>
<div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;<span class="stringliteral">      x_axis = A non-zero 3D vector in the plane that determines the X axis</span></div>
<div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;<span class="stringliteral">               direction.</span></div>
<div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;<span class="stringliteral">      y_axis = A non-zero 3D vector not parallel to x_axis that is used</span></div>
<div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;<span class="stringliteral">               to determine the Y axis direction. Note, y_axis does not</span></div>
<div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;<span class="stringliteral">               have to be perpendicular to x_axis.</span></div>
<div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;<span class="stringliteral">      The plane if successful. </span></div>
<div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;    origin = rhutil.coerce3dpoint(origin, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;    x_axis = rhutil.coerce3dvector(x_axis, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;    y_axis = rhutil.coerce3dvector(y_axis, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;    <span class="keywordflow">return</span> Rhino.Geometry.Plane(origin, x_axis, y_axis)</div>
<div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;</div>
<div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;</div>
<div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;<span class="keyword">def </span>PlaneFromNormal(origin, normal, xaxis=None):</div>
<div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Creates a plane from an origin point and a normal direction vector.</span></div>
<div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;<span class="stringliteral">      origin = A 3D point identifying the origin of the plane.</span></div>
<div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;<span class="stringliteral">      normal = A 3D vector identifying the normal direction of the plane.</span></div>
<div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;<span class="stringliteral">      xaxis[opt] = optional vector defining the plane&#39;s x-axis</span></div>
<div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;<span class="stringliteral">      The plane if successful.</span></div>
<div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;    origin = rhutil.coerce3dpoint(origin, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;    normal = rhutil.coerce3dvector(normal, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;    rc = Rhino.Geometry.Plane(origin, normal)</div>
<div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;    <span class="keywordflow">if</span> xaxis:</div>
<div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;        xaxis = rhutil.coerce3dvector(xaxis, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;        xaxis = Rhino.Geometry.Vector3d(xaxis)<span class="comment">#prevent original xaxis parameter from being unitized too</span></div>
<div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;        xaxis.Unitize()</div>
<div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;        yaxis = Rhino.Geometry.Vector3d.CrossProduct(rc.Normal, xaxis)</div>
<div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        rc = Rhino.Geometry.Plane(origin, xaxis, yaxis)</div>
<div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;    <span class="keywordflow">return</span> rc</div>
<div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;</div>
<div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;</div>
<div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;<span class="keyword">def </span>PlaneFromPoints(origin, x, y):</div>
<div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Creates a plane from three non-colinear points</span></div>
<div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;<span class="stringliteral">      origin = origin point of the plane</span></div>
<div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;<span class="stringliteral">      x, y = points on the plane&#39;s x and y axes</span></div>
<div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    origin = rhutil.coerce3dpoint(origin, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;    x = rhutil.coerce3dpoint(x, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;    y = rhutil.coerce3dpoint(y, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;    plane = Rhino.Geometry.Plane(origin, x, y)</div>
<div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;    <span class="keywordflow">if</span> plane.IsValid: <span class="keywordflow">return</span> plane</div>
<div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;</div>
<div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;</div>
<div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;<span class="keyword">def </span>PlanePlaneIntersection(plane1, plane2):</div>
<div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Calculates the intersection of two planes</span></div>
<div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;<span class="stringliteral">    Paramters:</span></div>
<div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;<span class="stringliteral">      plane1, plane2 = two planes</span></div>
<div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;<span class="stringliteral">      two 3d points identifying the starting/ending points of the intersection</span></div>
<div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;<span class="stringliteral">      None on error</span></div>
<div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;    plane1 = rhutil.coerceplane(plane1, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;    plane2 = rhutil.coerceplane(plane2, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;    rc, line = Rhino.Geometry.Intersect.Intersection.PlanePlane(plane1, plane2)</div>
<div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;    <span class="keywordflow">if</span> rc: <span class="keywordflow">return</span> line.From, line.To</div>
<div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;</div>
<div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;</div>
<div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;<span class="keyword">def </span>PlaneSphereIntersection(plane, sphere_plane, sphere_radius):</div>
<div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Calculates the intersection of a plane and a sphere</span></div>
<div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;<span class="stringliteral">      plane = the plane to intersect</span></div>
<div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;<span class="stringliteral">      sphere_plane = equitorial plane of the sphere. origin of the plane is</span></div>
<div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;<span class="stringliteral">        the center of the sphere</span></div>
<div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;<span class="stringliteral">      sphere_radius = radius of the sphere</span></div>
<div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;<span class="stringliteral">      list of intersection results - see help</span></div>
<div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;<span class="stringliteral">      None on error</span></div>
<div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;    sphere_plane = rhutil.coerceplane(sphere_plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;    sphere = Rhino.Geometry.Sphere(sphere_plane, sphere_radius)</div>
<div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;    rc, circle = Rhino.Geometry.Intersect.Intersection.PlaneSphere(plane, sphere)</div>
<div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;    <span class="keywordflow">if</span> rc==Rhino.Geometry.Intersect.PlaneSphereIntersection.Point:</div>
<div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;        <span class="keywordflow">return</span> 0, circle.Center</div>
<div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;    <span class="keywordflow">if</span> rc==Rhino.Geometry.Intersect.PlaneSphereIntersection.Circle:</div>
<div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;        <span class="keywordflow">return</span> 1, circle.Plane, circle.Radius</div>
<div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;</div>
<div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;</div>
<div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160;<span class="keyword">def </span>PlaneTransform(plane, xform):</div>
<div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Transforms a plane</span></div>
<div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;<span class="stringliteral">      plane = Plane to transform</span></div>
<div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;<span class="stringliteral">      xform = Transformation to apply</span></div>
<div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    xform = rhutil.coercexform(xform, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;    rc = Rhino.Geometry.Plane(plane)</div>
<div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;    <span class="keywordflow">if</span> rc.Transform(xform): <span class="keywordflow">return</span> rc</div>
<div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;</div>
<div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;</div>
<div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;<span class="keyword">def </span>RotatePlane(plane, angle_degrees, axis):</div>
<div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Rotates a plane</span></div>
<div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;<span class="stringliteral">    Parameters:</span></div>
<div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;<span class="stringliteral">      plane = Plane to rotate</span></div>
<div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160;<span class="stringliteral">      angle_degrees = rotation angle in degrees</span></div>
<div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;<span class="stringliteral">      axis = Vector3d or list of three numbers</span></div>
<div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;<span class="stringliteral">    Returns:</span></div>
<div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160;<span class="stringliteral">      rotated plane on success</span></div>
<div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;<span class="stringliteral">    &quot;&quot;&quot;</span></div>
<div class="line"><a name="l00232"></a><span class="lineno">  232</span>&#160;    plane = rhutil.coerceplane(plane, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00233"></a><span class="lineno">  233</span>&#160;    axis = rhutil.coerce3dvector(axis, <span class="keyword">True</span>)</div>
<div class="line"><a name="l00234"></a><span class="lineno">  234</span>&#160;    angle_radians = math.radians(angle_degrees)</div>
<div class="line"><a name="l00235"></a><span class="lineno">  235</span>&#160;    rc = Rhino.Geometry.Plane(plane)</div>
<div class="line"><a name="l00236"></a><span class="lineno">  236</span>&#160;    <span class="keywordflow">if</span> rc.Rotate(angle_radians, axis): <span class="keywordflow">return</span> rc</div>
<div class="line"><a name="l00237"></a><span class="lineno">  237</span>&#160;</div>
<div class="line"><a name="l00238"></a><span class="lineno">  238</span>&#160;</div>
<div class="line"><a name="l00239"></a><span class="lineno">  239</span>&#160;<span class="keyword">def </span>WorldXYPlane():</div>
<div class="line"><a name="l00240"></a><span class="lineno">  240</span>&#160;    <span class="stringliteral">&quot;Returns Rhino&#39;s world XY plane&quot;</span></div>
<div class="line"><a name="l00241"></a><span class="lineno">  241</span>&#160;    <span class="keywordflow">return</span> Rhino.Geometry.Plane.WorldXY</div>
<div class="line"><a name="l00242"></a><span class="lineno">  242</span>&#160;</div>
<div class="line"><a name="l00243"></a><span class="lineno">  243</span>&#160;</div>
<div class="line"><a name="l00244"></a><span class="lineno">  244</span>&#160;<span class="keyword">def </span>WorldYZPlane():</div>
<div class="line"><a name="l00245"></a><span class="lineno">  245</span>&#160;    <span class="stringliteral">&quot;Returns Rhino&#39;s world YZ plane&quot;</span></div>
<div class="line"><a name="l00246"></a><span class="lineno">  246</span>&#160;    <span class="keywordflow">return</span> Rhino.Geometry.Plane.WorldYZ</div>
<div class="line"><a name="l00247"></a><span class="lineno">  247</span>&#160;</div>
<div class="line"><a name="l00248"></a><span class="lineno">  248</span>&#160;</div>
<div class="line"><a name="l00249"></a><span class="lineno">  249</span>&#160;<span class="keyword">def </span>WorldZXPlane():</div>
<div class="line"><a name="l00250"></a><span class="lineno">  250</span>&#160;    <span class="stringliteral">&quot;Returns Rhino&#39;s world ZX plane&quot;</span></div>
<div class="line"><a name="l00251"></a><span class="lineno">  251</span>&#160;    <span class="keywordflow">return</span> Rhino.Geometry.Plane.WorldZX</div>
</div><!-- fragment --></div><!-- contents -->
</div><!-- doc-content -->
<!-- HTML footer for doxygen 1.8.9.1-->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a class="el" href="dir_498fa6d7fadccabe7b36c98a7b98e64b.html">rhinoscriptsyntax</a></li><li class="navelem"><a class="el" href="dir_50c1069cab179abf171fcff507cfe76b.html">Scripts</a></li><li class="navelem"><a class="el" href="dir_efda7f8bc7876f22620c0ac8c5470b21.html">rhinoscript</a></li><li class="navelem"><b>plane.py</b></li>
    <li class="footer">Generated on Tue Jun 30 2015 13:49:37 for rhinoscriptsyntax API docs by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.8.9.1 </li>
  </ul>
</div>
</body>
</html>
