gXMLBuffer="<?xml version=\"1.0\" encoding=\"UTF-8\"?><ck><di ky=\"59\" rd=\"modules/application/statusbarmessage.htm|StatusBarMessage\" ct=\"  StatusBarMessage  Sets Rhino&apos;s status bar message pane.  Syntax  rhinoscriptsyntax.Sta ...\"/><di ky=\"60\" rd=\"modules/application/statusbarpoint.htm|StatusBarPoint\" ct=\"  StatusBarPoint  Sets Rhino&apos;s status bar point coordinate panes.  Syntax  rhinoscriptsy ...\"/><di ky=\"61\" rd=\"modules/application/statusbarprogressmeter.htm|StatusBarProgressMeter\" ct=\"  StatusBarProgressMeter  Manipulates Rhino&apos;s status bar progress meter.  Syntax  Start, ...\"/><di ky=\"62\" rd=\"modules/application/templatefile.htm|TemplateFile\" ct=\"  TemplateFile  Returns or sets Rhino&apos;s default template file. The default template file is  ...\"/><di ky=\"63\" rd=\"modules/application/templatefolder.htm|TemplateFolder\" ct=\"  TemplateFolder  Returns or sets the location of Rhino&apos;s template files.  Syntax  rhino ...\"/><di ky=\"64\" rd=\"modules/application/windowhandle.htm|WindowHandle\" ct=\"  WindowHandle  Returns the Windows handle of Rhino&apos;s main window.  Syntax  rhinoscripts ...\"/><di ky=\"65\" rd=\"modules/application/workingfolder.htm|WorkingFolder\" ct=\"  WorkingFolder  Returns or sets Rhino&apos;s working directory, or folder.  The working  folde ...\"/><di ky=\"66\" rd=\"modules/block/addblock.htm|AddBlock\" ct=\"  AddBlock  Adds a new block definition to the document.  Syntax  rhinoscriptsyntax.AddB ...\"/><di ky=\"67\" rd=\"modules/block/blockcontainercount.htm|BlockContainerCount\" ct=\"  BlockContainerCount  Returns the number of block definitions that contain a specified bloc ...\"/><di ky=\"68\" rd=\"modules/block/blockcontainers.htm|BlockContainers\" ct=\"  BlockContainers  Returns the names of the block definitions that contain a specified block ...\"/><di ky=\"69\" rd=\"modules/block/blockcount.htm|BlockCount\" ct=\"  BlockCount  Returns the number of block definitions in the document.  Syntax  rhinoscr ...\"/><di ky=\"70\" rd=\"modules/block/blockdescription.htm|BlockDescription\" ct=\"  BlockDescription  Returns or sets the description of a block definition.  Syntax  rhin ...\"/><di ky=\"71\" rd=\"modules/block/blockinstancecount.htm|BlockInstanceCount\" ct=\"  BlockInstanceCount  Counts the number of instances of the block in the document.  Syntax ...\"/><di ky=\"72\" rd=\"modules/block/blockinstanceinsertpoint.htm|BlockInstanceInsertPoint\" ct=\"  BlockInstanceInsertPoint  Returns the insertion point of a block instance.  Syntax  rh ...\"/><di ky=\"73\" rd=\"modules/block/blockinstancename.htm|BlockInstanceName\" ct=\"  BlockInstanceName  Returns the block name of a block instance.  Syntax  rhinoscriptsyn ...\"/><di ky=\"74\" rd=\"modules/block/blockinstances.htm|BlockInstances\" ct=\"  BlockInstances  Returns the identifiers of the inserted instances of a block.  Syntax  ...\"/><di ky=\"75\" rd=\"modules/block/blockinstancexform.htm|BlockInstanceXform\" ct=\"  BlockInstanceXform  Returns the location of a block instance relative to the world coordin ...\"/><di ky=\"76\" rd=\"modules/block/blocknames.htm|BlockNames\" ct=\"  BlockNames  Returns the names of all block definitions in the document.  Syntax  rhino ...\"/><di ky=\"77\" rd=\"modules/block/blockobjectcount.htm|BlockObjectCount\" ct=\"  BlockObjectCount  Returns the number of objects that make up a block definition.  Syntax ...\"/><di ky=\"78\" rd=\"modules/block/blockobjects.htm|BlockObjects\" ct=\"  BlockObjects  Returns the identifiers of the objects that make up a block definition.  S ...\"/><di ky=\"79\" rd=\"modules/block/blockpath.htm|BlockPath\" ct=\"  BlockPath  Returns the path to the source of a linked or embedded block definition.  A lin ...\"/><di ky=\"80\" rd=\"modules/block/blockstatus.htm|BlockStatus\" ct=\"  BlockStatus  Returns the status of a linked block.  Syntax  rhinoscriptsyntax.BlockSta ...\"/><di ky=\"81\" rd=\"modules/block/deleteblock.htm|DeleteBlock\" ct=\"  DeleteBlock  Deletes a block definition and all of it&apos;s inserted instances.  Syntax  r ...\"/><di ky=\"82\" rd=\"modules/block/insertblock.htm|InsertBlock\" ct=\"  InsertBlock  Inserts a block whose definition already exists in the document.  Syntax  ...\"/><di ky=\"83\" rd=\"modules/block/isblock.htm|IsBlock\" ct=\"  IsBlock  Verifies the existence of a block definition in the document.  Syntax  rhinoc ...\"/><di ky=\"84\" rd=\"modules/block/isblockembedded.htm|IsBlockEmbedded\" ct=\"  IsBlockEmbedded  Verifies that a block definition is embedded, or linked, from an external ...\"/><di ky=\"85\" rd=\"modules/block/isblockinstance.htm|IsBlockInstance\" ct=\"  IsBlockInstance  Verifies an object is a block instance.  Syntax  rhinocriptsyntax.IsB ...\"/><di ky=\"86\" rd=\"modules/block/isblockinuse.htm|IsBlockInUse\" ct=\"  IsBlockInUse  Verifies that a block definition is being used by an inserted instance.  S ...\"/><di ky=\"87\" rd=\"modules/block/isblockreference.htm|IsBlockReference\" ct=\"  IsBlockReference  Verifies that a block definition is from a reference file.  Syntax  ...\"/><di ky=\"88\" rd=\"modules/block/renameblock.htm|RenameBlock\" ct=\"  RenameBlock  Renames an existing block definition.  Syntax  rhinocsriptsyntax.RenameBl ...\"/><di ky=\"89\" rd=\"modules/curve/addarc.htm|AddArc\" ct=\"  AddArc  Adds an arc curve to the document.  Syntax  rhinoscriptsyntax.AddArc ( plane,  ...\"/><di ky=\"90\" rd=\"modules/curve/addarc3pt.htm|AddArc3Pt\" ct=\"  AddArc3Pt  Adds a 3-point arc curve to the document.  Syntax  rhinoscriptsyntax.AddArc ...\"/><di ky=\"91\" rd=\"modules/curve/addarcpttanpt.htm|AddArcPtTanPt\" ct=\"  AddArcPtTanPt  Adds an arc curve, created from a start point, a start direction, and an en ...\"/><di ky=\"92\" rd=\"modules/curve/addblendcurve.htm|AddBlendCurve\" ct=\"  AddBlendCurve  Makes a curve blend between two curves at the parameters specified with the ...\"/><di ky=\"93\" rd=\"modules/curve/addcircle.htm|AddCircle\" ct=\"  AddCircle  Adds a circle curve to the document.  Syntax  rhinoscriptsyntax.AddCircle(  ...\"/><di ky=\"94\" rd=\"modules/curve/addcircle3pt.htm|AddCircle3Pt\" ct=\"  AddCircle3Pt  Adds a 3-point circle curve to the document.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"95\" rd=\"modules/curve/addcurve.htm|AddCurve\" ct=\"  AddCurve  Adds a control points curve object to the document.  Syntax  rhinoscriptsynt ...\"/><di ky=\"96\" rd=\"modules/curve/addellipse.htm|AddEllipse\" ct=\"  AddEllipse  Adds an elliptical curve to the document.  Syntax  rhinoscriptsyntax.AddEl ...\"/><di ky=\"97\" rd=\"modules/curve/addellipse3pt.htm|AddEllipse3Pt\" ct=\"  AddEllipse3Pt  Adds a 3 point elliptical curve to the document.  Syntax  rhinoscriptsy ...\"/><di ky=\"98\" rd=\"modules/curve/addfilletcurve.htm|AddFilletCurve\" ct=\"  AddFilletCurve  Adds a fillet curve between two curve objects.  Syntax  rhinoscriptsyn ...\"/><di ky=\"99\" rd=\"modules/curve/addinterpcrvonsrf.htm|AddInterpCrvOnSrf\" ct=\"  AddInterpCrvOnSrf  Adds an interpolated curve object that lies on a specified surface. Not ...\"/><di ky=\"100\" rd=\"modules/curve/addinterpcrvonsrfuv.htm|AddInterpCrvOnSrfUV\" ct=\"  AddInterpCrvOnSrfUV  Adds an interpolated curve object. based on surface parameters, that  ...\"/><di ky=\"101\" rd=\"modules/curve/addinterpcurve.htm|AddInterpCurve\" ct=\"  AddInterpCurve  Adds an interpolated curve object to  the document.  Options exist to make ...\"/><di ky=\"102\" rd=\"modules/curve/addline.htm|AddLine\" ct=\"  AddLine  Adds a line curve to the current model.  Syntax  rhinoscriptsyntax.AddLine (s ...\"/><di ky=\"103\" rd=\"modules/curve/addnurbscurve.htm|AddNurbsCurve\" ct=\"  AddNurbsCurve  Adds a NURBS curve object to the document.  Syntax  rhinoscriptsyntax.A ...\"/><di ky=\"104\" rd=\"modules/curve/addpolyline.htm|AddPolyline\" ct=\"  AddPolyline  Adds a polyline curve object to the current model.  Syntax  rhinoscriptsy ...\"/><di ky=\"105\" rd=\"modules/curve/addrectangle.htm|AddRectangle\" ct=\"  AddRectangle  Adds a rectangular curve to the document.  Syntax  rhinoscriptsyntax.Add ...\"/><di ky=\"106\" rd=\"modules/curve/addspiral.htm|AddSpiral\" ct=\"  AddSpiral  Adds a spiral or helical curve object to the document.  Syntax  rhinoscript ...\"/><di ky=\"107\" rd=\"modules/curve/addsubcrv.htm|AddSubCrv\" ct=\"  AddSubCrv  Adds a new curve object based on a portion, or interval, of an existing curve o ...\"/><di ky=\"108\" rd=\"modules/curve/arcangle.htm|ArcAngle\" ct=\"  ArcAngle  Returns the angle of an arc curve object.  Syntax  rhinoscriptsyntax.ArcAngl ...\"/><di ky=\"109\" rd=\"modules/curve/arccenterpoint.htm|ArcCenterPoint\" ct=\"  ArcCenterPoint  Returns the center point of an arc curve object.  Syntax  rhinoscripts ...\"/><di ky=\"110\" rd=\"modules/curve/arcmidpoint.htm|ArcMidPoint\" ct=\"  ArcMidPoint  Returns the mid point of an arc curve object.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"111\" rd=\"modules/curve/arcradius.htm|ArcRadius\" ct=\"  ArcRadius  Returns the radius of an arc curve object.  Syntax  rhinoscriptsyntax.ArcRa ...\"/><di ky=\"112\" rd=\"modules/curve/changecurvedegree.htm|ChangeCurveDegree\" ct=\"  ChangeCurveDegree  Changes the degree of a curve object. For more information see the Rhin ...\"/><di ky=\"113\" rd=\"modules/curve/circlecenterpoint.htm|CircleCenterPoint\" ct=\"  CircleCenterPoint  Returns the center point of a circle curve object.  Syntax  rhinosc ...\"/><di ky=\"114\" rd=\"modules/curve/circlecircumference.htm|CircleCircumference\" ct=\"  CircleCircumference  Returns the circumference of a circle curve object.  Syntax  rhin ...\"/><di ky=\"115\" rd=\"modules/curve/circleradius.htm|CircleRadius\" ct=\"  CircleRadius  Returns the radius of a circle curve object.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"116\" rd=\"modules/curve/closecurve.htm|CloseCurve\" ct=\"  CloseCurve  Closes an open curve object by making adjustments to the end points so that th ...\"/><di ky=\"117\" rd=\"modules/curve/closedcurveorientation.htm|ClosedCurveOrientation\" ct=\"  ClosedCurveOrientation  Determine the orientation (counter-clockwise or clockwise) of a cl ...\"/><di ky=\"118\" rd=\"modules/curve/convertcurvetopolyline.htm|ConvertCurveToPolyline\" ct=\"  ConvertCurveToPolyline  Converts a curve to a polyline curve.  Syntax  rhinoscriptsynt ...\"/></ck>";