gXMLBuffer="<?xml version=\"1.0\" encoding=\"UTF-8\"?><ck><di ky=\"588\" rd=\"modules/pointvector/vectorcreate.htm|VectorCreate\" ct=\"  VectorCreate  Creates a vector from two 3-D points.  Syntax  rhinoscriptsyntax.VectorC ...\"/><di ky=\"589\" rd=\"modules/pointvector/vectorcrossproduct.htm|VectorCrossProduct\" ct=\"  VectorCrossProduct  Calculates the cross product of two 3-D vectors.  Syntax  rhinoscr ...\"/><di ky=\"590\" rd=\"modules/pointvector/vectordivide.htm|VectorDivide\" ct=\"  VectorDivide  Divides a 3-D vectors by a value  Syntax  rhinoscriptsyntax.VectorDivide ...\"/><di ky=\"591\" rd=\"modules/pointvector/vectordotproduct.htm|VectorDotProduct\" ct=\"  VectorDotProduct  Calculates the dot product of two 3-D vectors.  Syntax  rhinoscripts ...\"/><di ky=\"592\" rd=\"modules/pointvector/vectorlength.htm|VectorLength\" ct=\"  VectorLength  Returns the length of a 3-D vector.  Syntax  rhinoscriptsyntax.VectorLen ...\"/><di ky=\"593\" rd=\"modules/pointvector/vectormultiply.htm|VectorMultiply\" ct=\"  VectorMultiply  Multiplies two 3-D vectors.  Syntax  rhinoscriptsyntax.VectorMultiply  ...\"/><di ky=\"594\" rd=\"modules/pointvector/vectorreverse.htm|VectorReverse\" ct=\"  VectorReverse  Reverses the direction of a 3-D vector.  Syntax  rhinoscriptsyntax.Vect ...\"/><di ky=\"595\" rd=\"modules/pointvector/vectorrotate.htm|VectorRotate\" ct=\"  VectorRotate  Rotates a 3-D vector.  Syntax  rhinoscriptsyntax.VectorRotate (vector, a ...\"/><di ky=\"596\" rd=\"modules/pointvector/vectorscale.htm|VectorScale\" ct=\"  VectorScale  Scales a 3-D vector.  Syntax  rhinoscriptsyntax.VectorScale (vector, scal ...\"/><di ky=\"597\" rd=\"modules/pointvector/vectorsubtract.htm|VectorSubtract\" ct=\"  VectorSubtract  Subtracts two 3-D vectors.  Syntax  rhinoscriptsyntax.VectorSubtract ( ...\"/><di ky=\"598\" rd=\"modules/pointvector/vectortransform.htm|VectorTransform\" ct=\"  VectorTransform  Transforms a 3-D vector.  Syntax  rhinoscriptsyntax.VectorTransform ( ...\"/><di ky=\"599\" rd=\"modules/pointvector/vectorunitize.htm|VectorUnitize\" ct=\"  VectorUnitize  Unitizes, or normalizes, a 3-D vector. Note, zero vectors cannot be unitize ...\"/><di ky=\"600\" rd=\"modules/selection/allobjects.htm|AllObjects\" ct=\"  AllObjects  Returns the identifiers of all objects in the document.  Syntax  rhinoscri ...\"/><di ky=\"601\" rd=\"modules/selection/firstobject.htm|FirstObject\" ct=\"  FirstObject  Returns the identifier of the first object in the document.  The first object ...\"/><di ky=\"602\" rd=\"modules/selection/getcurveobject.htm|GetCurveObject\" ct=\"  GetCurveObject  Prompts the user to pick, or select, a single curve object.  Syntax  r ...\"/><di ky=\"603\" rd=\"modules/selection/getobject.htm|GetObject\" ct=\"  GetObject  Prompts the user to pick, or select, a single object.  Syntax  rhinoscripts ...\"/><di ky=\"604\" rd=\"modules/selection/getobjectex.htm|GetObjectEx\" ct=\"  GetObjectEx  Prompts the user to pick, or select, a single object.  Syntax  rhinoscrip ...\"/><di ky=\"605\" rd=\"modules/selection/getobjects.htm|GetObjects\" ct=\"  GetObjects  Prompts the user to pick or select one or more objects.  Syntax  rhinoscri ...\"/><di ky=\"606\" rd=\"modules/selection/getobjectsex.htm|GetObjectsEx\" ct=\"  GetObjectsEx  Prompts the user to pick or select one or more objects.  Syntax  rhinosc ...\"/><di ky=\"607\" rd=\"modules/selection/getpointcoordinates.htm|GetPointCoordinates\" ct=\"  GetPointCoordinates  Prompts the user to pick or select one or more point objects. Unlike  ...\"/><di ky=\"608\" rd=\"modules/selection/getsurfaceobject.htm|GetSurfaceObject\" ct=\"  GetSurfaceObject  Prompts the user to pick, or select, a single surface object.  Syntax ...\"/><di ky=\"609\" rd=\"modules/selection/hiddenobjects.htm|HiddenObjects\" ct=\"  HiddenObjects  Returns the identifiers of all hidden objects in the document.  Hidden obje ...\"/><di ky=\"610\" rd=\"modules/selection/invertselectedobjects.htm|InvertSelectedObjects\" ct=\"  InvertSelectedObjects  Inverts the current object selection.  The identifiers of the newly ...\"/><di ky=\"611\" rd=\"modules/selection/lastcreatedobjects.htm|LastCreatedObjects\" ct=\"  LastCreatedObjects  Returns the identifiers of the objects that were most recently created ...\"/><di ky=\"612\" rd=\"modules/selection/lastobject.htm|LastObject\" ct=\"  LastObject  Returns the identifier of the last object in the document.  The last object in ...\"/><di ky=\"613\" rd=\"modules/selection/lockedobjects.htm|LockedObjects\" ct=\"  LockedObjects  Returns the identifiers of all locked objects in the document.  Visible   ...\"/><di ky=\"614\" rd=\"modules/selection/nextobject.htm|NextObject\" ct=\"  NextObject  Returns the identifier of the next object in the document.  Syntax  rhinos ...\"/><di ky=\"615\" rd=\"modules/selection/normalobjects.htm|NormalObjects\" ct=\"  NormalObjects  Returns the identifiers of all normal objects in the document.  Normal obje ...\"/><di ky=\"616\" rd=\"modules/selection/objectsbycolor.htm|ObjectsByColor\" ct=\"  ObjectsByColor  Returns the identifiers of all objects based on the objects&apos; color.  Objec ...\"/><di ky=\"617\" rd=\"modules/selection/objectsbygroup.htm|ObjectsByGroup\" ct=\"  ObjectsByGroup  Returns the identifiers of all objects based on the objects&apos; group name.  ...\"/><di ky=\"618\" rd=\"modules/selection/objectsbylayer.htm|ObjectsByLayer\" ct=\"  ObjectsByLayer  Returns the identifiers of all objects based on the objects&apos; layer.  Syn ...\"/><di ky=\"619\" rd=\"modules/selection/objectsbyname.htm|ObjectsByName\" ct=\"  ObjectsByName  Returns the identifiers of all objects based on the objects&apos; user-assigned  ...\"/><di ky=\"620\" rd=\"modules/selection/objectsbytype.htm|ObjectsByType\" ct=\"  ObjectsByType  Returns the identifiers of all objects based on the objects&apos; geometry type. ...\"/><di ky=\"621\" rd=\"modules/selection/selectedobjects.htm|SelectedObjects\" ct=\"  SelectedObjects  Returns the identifiers of all objects that are currently selected.  Sy ...\"/><di ky=\"622\" rd=\"modules/selection/selection_module.htm|Selection Module\" ct=\"  Selection Methods  The following methods are available for selecting and obtaining the ide ...\"/><di ky=\"623\" rd=\"modules/selection/unselectallobjects.htm|UnselectAllObjects\" ct=\"  UnselectAllObjects  Unselects all objects in the document.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"624\" rd=\"modules/selection/visibleobjects.htm|VisibleObjects\" ct=\"  VisibleObjects  Returns the identifiers of all objects that are visible in a specified vie ...\"/><di ky=\"625\" rd=\"modules/selection/windowpick.htm|WindowPick\" ct=\"  WindowPick  Picks objects using either a window or crossing selection.  Syntax  rhinos ...\"/><di ky=\"626\" rd=\"modules/surface/addbox.htm|AddBox\" ct=\"  AddBox  Adds a new box-shaped polysurface to the document.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"627\" rd=\"modules/surface/addcone.htm|AddCone\" ct=\"  AddCone  Adds a cone-shaped polysurface to the document.  Syntax  rhinoscriptsyntax.Ad ...\"/><di ky=\"628\" rd=\"modules/surface/addcutplane.htm|AddCutPlane\" ct=\"  AddCutPlane  Adds a planar surface through objects at a designated location.  For more inf ...\"/><di ky=\"629\" rd=\"modules/surface/addcylinder.htm|AddCylinder\" ct=\"  AddCylinder  Adds a cylinder-shaped polysurface to the document.  Syntax  rhinoscripts ...\"/><di ky=\"630\" rd=\"modules/surface/addedgesrf.htm|AddEdgeSrf\" ct=\"  AddEdgeSrf  Creates a surface from 2, 3, or 4 edge curves.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"631\" rd=\"modules/surface/addloftsrf.htm|AddLoftSrf\" ct=\"  AddLoftSrf  Adds a surface created by lofting curves to the document.    This functi ...\"/><di ky=\"632\" rd=\"modules/surface/addnetworksrf.htm|AddNetworkSrf\" ct=\"  AddNetworkSrf  Creates a surface from a network of crossing curves. Note: All curves  in ...\"/><di ky=\"633\" rd=\"modules/surface/addnurbssurface.htm|AddNurbsSurface\" ct=\"  AddNurbsSurface  Adds a NURBS surface object to the document.  Syntax  rhinoscriptsynt ...\"/><di ky=\"634\" rd=\"modules/surface/addpipe.htm|AddPipe\" ct=\"  AddPipe  Creates a singled-walled surface with a circular profile around a curve.  Synta ...\"/><di ky=\"635\" rd=\"modules/surface/addplanarsrf.htm|AddPlanarSrf\" ct=\"  AddPlanarSrf  Creates one or more surfaces from planar curves.  Syntax  rhinoscriptsyn ...\"/><di ky=\"636\" rd=\"modules/surface/addplanesurface.htm|AddPlaneSurface\" ct=\"  AddPlaneSurface  Creates a plane surface.  Syntax  rhinoscriptsyntax.AddPlaneSurface ( ...\"/><di ky=\"637\" rd=\"modules/surface/addrevsrf.htm|AddRevSrf\" ct=\"  AddRevSrf  Create a surface by revolving a curve around an axis.  Syntax  rhinoscripts ...\"/><di ky=\"638\" rd=\"modules/surface/addsphere.htm|AddSphere\" ct=\"  AddSphere  Adds a spherical surface to the document.  Syntax  rhinoscriptsyntax.AddSph ...\"/><di ky=\"639\" rd=\"modules/surface/addsrfcontourcrvs.htm|AddSrfContourCrvs\" ct=\"  AddSrfContourCrvs  Adds a spaced series of planar curves resulting from the intersection o ...\"/><di ky=\"640\" rd=\"modules/surface/addsrfcontrolptgrid.htm|AddSrfControlPtGrid\" ct=\"  AddSrfControlPtGrid  Creates a surface from a grid of control points.  Syntax  rhinosc ...\"/><di ky=\"641\" rd=\"modules/surface/addsrfpt.htm|AddSrfPt\" ct=\"  AddSrfPt  Creates a new surface from either 3 or 4 corner points.  Syntax  rhinoscript ...\"/><di ky=\"642\" rd=\"modules/surface/addsrfptgrid.htm|AddSrfPtGrid\" ct=\"  AddSrfPtGrid  Creates a surface from a grid of points.  Syntax  rhinoscriptsyntax.AddS ...\"/><di ky=\"643\" rd=\"modules/surface/addsweep1.htm|AddSweep1\" ct=\"  AddSweep1  Adds a surface created through profile curves that define the surface shape and ...\"/><di ky=\"644\" rd=\"modules/surface/addsweep2.htm|AddSweep2\" ct=\"  AddSweep2  Adds a surface created through profile curves that define the surface shape and ...\"/><di ky=\"645\" rd=\"modules/surface/addtorus.htm|AddTorus\" ct=\"  AddTorus  Adds a torus-shaped revolved surface to the document.  Syntax  rhinoscriptsy ...\"/><di ky=\"646\" rd=\"modules/surface/booleandifference.htm|BooleanDifference\" ct=\"  BooleanDifference  Performs a Boolean difference operation on two sets of input surfaces a ...\"/></ck>";