gXMLBuffer="<?xml version=\"1.0\" encoding=\"UTF-8\"?><ck><di ky=\"647\" rd=\"modules/surface/booleanintersection.htm|BooleanIntersection\" ct=\"  BooleanIntersection  Performs a Boolean intersection operation on two sets of input surfac ...\"/><di ky=\"648\" rd=\"modules/surface/booleanunion.htm|BooleanUnion\" ct=\"  BooleanUnion  Performs a Boolean union operation on a set of input surfaces and polysurfac ...\"/><di ky=\"649\" rd=\"modules/surface/brepclosestpoint.htm|BrepClosestPoint\" ct=\"  BrepClosestPoint  Returns the point on a surface or polysurface that is closest to a test  ...\"/><di ky=\"650\" rd=\"modules/surface/capplanarholes.htm|CapPlanarHoles\" ct=\"  CapPlanarHoles  Caps planar holes in a surface or polysurface. For more details, see the  ...\"/><di ky=\"651\" rd=\"modules/surface/changesurfacedegree.htm|ChangeSurfaceDegree\" ct=\"  ChangeSurfaceDegree  Changes the degree of a surface object.  For more information see   ...\"/><di ky=\"652\" rd=\"modules/surface/duplicateedgecurves.htm|DuplicateEdgeCurves\" ct=\"  DuplicateEdgeCurves  Duplicates the edge curves of a surface or polysurface. For more info ...\"/><di ky=\"653\" rd=\"modules/surface/duplicatesurfaceborder.htm|DuplicateSurfaceBorder\" ct=\"  DuplicateSurfaceBorder  Creates a curve that duplicates a surface or polysurface border.  ...\"/><di ky=\"654\" rd=\"modules/surface/evaluatesurface.htm|EvaluateSurface\" ct=\"  EvaluateSurface  Evaluates a surface at a U,V parameter.  Syntax  rhinoscriptsyntax.Ev ...\"/><di ky=\"655\" rd=\"modules/surface/explodepolysurfaces.htm|ExplodePolysurfaces\" ct=\"  ExplodePolysurfaces  Explodes, or un-joins,  one more polysurface objects.  Polysurfaces w ...\"/><di ky=\"656\" rd=\"modules/surface/extendsurface.htm|ExtendSurface\" ct=\"  ExtendSurface  Lengthens an untrimmed surface object by a factor value.  Syntax  rhino ...\"/><di ky=\"657\" rd=\"modules/surface/extractisocurve.htm|ExtractIsoCurve\" ct=\"  ExtractIsoCurve  Extracts isoparametric curves from a surface.  Syntax  rhinoscriptsyn ...\"/><di ky=\"658\" rd=\"modules/surface/extractsurface.htm|ExtractSurface\" ct=\"  ExtractSurface  Separates or copies a surface (face) or a copy of a surface from a polysur ...\"/><di ky=\"659\" rd=\"modules/surface/extrudecurve.htm|ExtrudeCurve\" ct=\"  ExtrudeCurve  Creates a surface by extruding a curve along a path curve.  Syntax  rhin ...\"/><di ky=\"660\" rd=\"modules/surface/extrudecurvepoint.htm|ExtrudeCurvePoint\" ct=\"  ExtrudeCurvePoint  Creates a surface by extruding a curve to a point.  Syntax  rhinosc ...\"/><di ky=\"661\" rd=\"modules/surface/extrudecurvestraight.htm|ExtrudeCurveStraight\" ct=\"  ExtrudeCurveStraight  Creates a surface by extruding a curve straight along two points tha ...\"/><di ky=\"662\" rd=\"modules/surface/extrudesurface.htm|ExtrudeSurface\" ct=\"  ExtrudeSurface  Creates a surface or solid by extruding straight along a path curve.  Sy ...\"/><di ky=\"663\" rd=\"modules/surface/filletsurfaces.htm|FilletSurfaces\" ct=\"  FilletSurfaces  Create constant radius rolling ball fillets between two surfaces. Note, th ...\"/><di ky=\"664\" rd=\"modules/surface/flipsurface.htm|FlipSurface\" ct=\"  FlipSurface  Returns or changes the normal direction of a surface. This feature can also b ...\"/><di ky=\"665\" rd=\"modules/surface/intersectbreps.htm|IntersectBreps\" ct=\"  IntersectBreps  Intersects a brep object with another  brep object. Note, unlike the  Surf ...\"/><di ky=\"666\" rd=\"modules/surface/intersectspheres.htm|IntersectSpheres\" ct=\"  IntersectSpheres  Calculates the intersection of two spheres.     Syntax  rhinoscript. ...\"/><di ky=\"667\" rd=\"modules/surface/isbrep.htm|IsBrep\" ct=\"  IsBrep  Verifies an object is a Brep, or a boundary representation model, object.  Synta ...\"/><di ky=\"668\" rd=\"modules/surface/iscone.htm|IsCone\" ct=\"  IsCone  Determines if a surface is a portion of a cone.  Syntax  rhinoscriptsyntax.IsC ...\"/><di ky=\"669\" rd=\"modules/surface/iscylinder.htm|IsCylinder\" ct=\"  IsCylinder  Determines if a surface is a portion of a cylinder.  Syntax  rhinoscriptsy ...\"/><di ky=\"670\" rd=\"modules/surface/isplanesurface.htm|IsPlaneSurface\" ct=\"  IsPlaneSurface  Verifies an object is a plane surface. Plane surfaces can be created by th ...\"/><di ky=\"671\" rd=\"modules/surface/ispointinsurface.htm|IsPointInSurface\" ct=\"  IsPointInSurface  Verifies that a point is inside a closed surface or polysurface.  Synt ...\"/><di ky=\"672\" rd=\"modules/surface/ispointonsurface.htm|IsPointOnSurface\" ct=\"  IsPointOnSurface  Verifies that a point lies on a surface.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"673\" rd=\"modules/surface/ispolysurface.htm|IsPolysurface\" ct=\"  IsPolysurface  Verifies an object is a polysurface.  Polysurfaces consists of two or more  ...\"/><di ky=\"674\" rd=\"modules/surface/ispolysurfaceclosed.htm|IsPolysurfaceClosed\" ct=\"  IsPolysurfaceClosed  Verifies a polysurface object is closed.  If the polysurface fully en ...\"/><di ky=\"675\" rd=\"modules/surface/issphere.htm|IsSphere\" ct=\"  IsSphere  Determines if a surface is a portion of a sphere.  Syntax  rhinoscriptsyntax ...\"/><di ky=\"676\" rd=\"modules/surface/issurface.htm|IsSurface\" ct=\"  IsSurface  Verifies an object is surface.  Brep objects with only one face are also consid ...\"/><di ky=\"677\" rd=\"modules/surface/issurfaceclosed.htm|IsSurfaceClosed\" ct=\"  IsSurfaceClosed  Verifies a surface object is closed in the specified direction.  If the s ...\"/><di ky=\"678\" rd=\"modules/surface/issurfaceperiodic.htm|IsSurfacePeriodic\" ct=\"  IsSurfacePeriodic  Verifies a surface object is periodic in the specified direction.  Sy ...\"/><di ky=\"679\" rd=\"modules/surface/issurfaceplanar.htm|IsSurfacePlanar\" ct=\"  IsSurfacePlanar  Verifies a surface object is planar.  Syntax  rhinoscriptsyntax.IsSur ...\"/><di ky=\"680\" rd=\"modules/surface/issurfacerational.htm|IsSurfaceRational\" ct=\"  IsSurfaceRational  Verifies a surface object is rational.  Syntax  rhinoscriptsyntax.I ...\"/><di ky=\"681\" rd=\"modules/surface/issurfacesingular.htm|IsSurfaceSingular\" ct=\"  IsSurfaceSingular  Verifies a surface object is singular in the specified direction.  Surf ...\"/><di ky=\"682\" rd=\"modules/surface/issurfacetrimmed.htm|IsSurfaceTrimmed\" ct=\"  IsSurfaceTrimmed  Verifies a surface object has been trimmed.  Syntax  rhinoscriptsynt ...\"/><di ky=\"683\" rd=\"modules/surface/istorus.htm|IsTorus\" ct=\"  IsTorus  Determines if a surface is a portion of a torus.  Syntax  rhinoscriptsyntax.I ...\"/><di ky=\"684\" rd=\"modules/surface/joinsurfaces.htm|JoinSurfaces\" ct=\"  JoinSurfaces  Joins two or more surface or polysurface objects together to form one polysu ...\"/><di ky=\"685\" rd=\"modules/surface/makesurfaceperiodic.htm|MakeSurfacePeriodic\" ct=\"  MakeSurfacePeriodic  Makes an existing surface a periodic NURBS surface.  Syntax  rhin ...\"/><di ky=\"686\" rd=\"modules/surface/offsetsurface.htm|OffsetSurface\" ct=\"  OffsetSurface  Offsets a trimmed or untrimmed surface by a distance. The offset surface wi ...\"/><di ky=\"687\" rd=\"modules/surface/pullcurve.htm|PullCurve\" ct=\"  PullCurve  Pulls a curve object to a surface object. For more information, see the Rhino h ...\"/><di ky=\"688\" rd=\"modules/surface/rebuildsurface.htm|RebuildSurface\" ct=\"  RebuildSurface  Rebuilds a surface to given degree and control point count.  For more info ...\"/><di ky=\"689\" rd=\"modules/surface/reversesurface.htm|ReverseSurface\" ct=\"  ReverseSurface  Reverses the U and V directions of a surface object. This feature can also ...\"/><di ky=\"690\" rd=\"modules/surface/shootray.htm|ShootRay\" ct=\"  ShootRay  Shoots a ray at a collection of surfaces.  Syntax  rhinoscriptsyntax.ShootRa ...\"/><di ky=\"691\" rd=\"modules/surface/shortpath.htm|ShortPath\" ct=\"  ShortPath  Creates the shortest possible curve (geodesic) between two points on a surface. ...\"/><di ky=\"692\" rd=\"modules/surface/shrinktrimmedsurface.htm|ShrinkTrimmedSurface\" ct=\"  ShrinkTrimmedSurface  Shrinks the underlying untrimmed surfaces near to trimming boundarie ...\"/><di ky=\"693\" rd=\"modules/surface/splitbrep.htm|SplitBrep\" ct=\"  SplitBrep  Splits a brep.  A brep can be either a surface with a single face or a polysurf ...\"/><di ky=\"694\" rd=\"modules/surface/surface_module.htm|Surface Module\" ct=\"  Surface &amp; Polysurface Methods  The following methods are available for creating, querying  ...\"/><di ky=\"695\" rd=\"modules/surface/surfacearea.htm|SurfaceArea\" ct=\"  SurfaceArea  Calculates the area of a surface or polysurface object. The results are based ...\"/><di ky=\"696\" rd=\"modules/surface/surfaceareacentroid.htm|SurfaceAreaCentroid\" ct=\"  SurfaceAreaCentroid  Calculates the area centroid of a surface or polysurface object.  S ...\"/><di ky=\"697\" rd=\"modules/surface/surfaceareamoments.htm|SurfaceAreaMoments\" ct=\"  SurfaceAreaMoments  Calculates the area moments of inertia of a surface or polysurface obj ...\"/><di ky=\"698\" rd=\"modules/surface/surfaceclosestpoint.htm|SurfaceClosestPoint\" ct=\"  SurfaceClosestPoint  Returns the UV parameter of the point on a surface that is closest to ...\"/><di ky=\"699\" rd=\"modules/surface/surfacecone.htm|SurfaceCone\" ct=\"  SurfaceCone  Returns the definition of a cone surface.  Syntax  rhinoscriptsyntax.Surf ...\"/><di ky=\"700\" rd=\"modules/surface/surfacecurvature.htm|SurfaceCurvature\" ct=\"  SurfaceCurvature  Returns the curvature of a surface at a U,V parameter.  See the Rhino he ...\"/><di ky=\"701\" rd=\"modules/surface/surfacecylinder.htm|SurfaceCylinder\" ct=\"  SurfaceCylinder  Returns the definition of a cylinder surface.  Syntax  rhinoscriptsyn ...\"/><di ky=\"702\" rd=\"modules/surface/surfacedegree.htm|SurfaceDegree\" ct=\"  SurfaceDegree  Returns the degree of a  surface object in the specified direction.  Synt ...\"/><di ky=\"703\" rd=\"modules/surface/surfacedomain.htm|SurfaceDomain\" ct=\"  SurfaceDomain  Returns the domain of a  surface object in the specified direction.  Synt ...\"/><di ky=\"704\" rd=\"modules/surface/surfaceeditpoints.htm|SurfaceEditPoints\" ct=\"  SurfaceEditPoints  Returns the edit, or Greville, points of a surface object.  For each su ...\"/></ck>";