gXMLBuffer="<?xml version=\"1.0\" encoding=\"UTF-8\"?><ck><di ky=\"119\" rd=\"modules/curve/curve_module.htm|Curve Module\" ct=\"  Curve Methods  The following methods are available for creating, querying or manipulating  ...\"/><di ky=\"120\" rd=\"modules/curve/curvearclengthpoint.htm|CurveArcLengthPoint\" ct=\"  CurveArcLengthPoint  Returns the point on the curve that is a specified arc length from th ...\"/><di ky=\"121\" rd=\"modules/curve/curvearea.htm|CurveArea\" ct=\"  CurveArea  Returns that area of closed planar curves. The results are based on the current ...\"/><di ky=\"122\" rd=\"modules/curve/curveareacentroid.htm|CurveAreaCentroid\" ct=\"  CurveAreaCentroid  Returns that area centroid of closed, planar curves. The results are ba ...\"/><di ky=\"123\" rd=\"modules/curve/curvearrows.htm|CurveArrows\" ct=\"  CurveArrows  Enables or disabled a curve object&apos;s annotation arrows.  Syntax  rhinoscr ...\"/><di ky=\"124\" rd=\"modules/curve/curvebooleandifference.htm|CurveBooleanDifference\" ct=\"  CurveBooleanDifference  Calculates the difference between two closed, planar curves and ad ...\"/><di ky=\"125\" rd=\"modules/curve/curvebooleanintersection.htm|CurveBooleanIntersection\" ct=\"  CurveBooleanIntersection  Calculates the intersection of two closed, planar curves and add ...\"/><di ky=\"126\" rd=\"modules/curve/curvebooleanunion.htm|CurveBooleanUnion\" ct=\"  CurveBooleanUnion  Calculates the union of two or more closed, planar curves and adds the  ...\"/><di ky=\"127\" rd=\"modules/curve/curvebrepintersect.htm|CurveBrepIntersect\" ct=\"  CurveBrepIntersect  Intersects a curve object with a brep object. Note, unlike the  CurveS ...\"/><di ky=\"128\" rd=\"modules/curve/curveclosestobject.htm|CurveClosestObject\" ct=\"  CurveClosestObject  Returns the 3-D point locations on two objects where they are closest  ...\"/><di ky=\"129\" rd=\"modules/curve/curveclosestpoint.htm|CurveClosestPoint\" ct=\"  CurveClosestPoint  Returns the parameter of the point on a curve that is closest to a test ...\"/><di ky=\"130\" rd=\"modules/curve/curvecontourpoints.htm|CurveContourPoints\" ct=\"  CurveContourPoints  Returns the 3-D point locations calculated by contouring a curve objec ...\"/><di ky=\"131\" rd=\"modules/curve/curvecurvature.htm|CurveCurvature\" ct=\"  CurveCurvature  Returns the curvature of a curve at a parameter.  See the Rhino help file  ...\"/><di ky=\"132\" rd=\"modules/curve/curvecurveintersection.htm|CurveCurveIntersection\" ct=\"  CurveCurveIntersection  Calculates the intersection of two curve objects.  Syntax  rhi ...\"/><di ky=\"133\" rd=\"modules/curve/curvedegree.htm|CurveDegree\" ct=\"  CurveDegree  Returns the degree of a curve object.  Syntax  rhinscriptsyntax.CurveDegr ...\"/><di ky=\"134\" rd=\"modules/curve/curvedeviation.htm|CurveDeviation\" ct=\"  CurveDeviation  Returns the minimum and maximum deviation between two curve objects. For m ...\"/><di ky=\"135\" rd=\"modules/curve/curvedim.htm|CurveDim\" ct=\"  CurveDim  Returns the dimension of a curve object.  Syntax  rhinoscriptsyntax.CurveDim ...\"/><di ky=\"136\" rd=\"modules/curve/curvedirectionsmatch.htm|CurveDirectionsMatch\" ct=\"  CurveDirectionsMatch  Tests if two curve objects are generally in the same direction or if ...\"/><di ky=\"137\" rd=\"modules/curve/curvediscontinuity.htm|CurveDiscontinuity\" ct=\"  CurveDiscontinuity  Search for a derivative, tangent, or curvature discontinuity in a curv ...\"/><di ky=\"138\" rd=\"modules/curve/curvedomain.htm|CurveDomain\" ct=\"  CurveDomain  Returns the domain of a curve object.  Syntax  rhinoscriptsyntax.CurveDom ...\"/><di ky=\"139\" rd=\"modules/curve/curveeditpoints.htm|CurveEditPoints\" ct=\"  CurveEditPoints  Returns the edit, or Greville, points of a curve object.  For each curve  ...\"/><di ky=\"140\" rd=\"modules/curve/curveendpoint.htm|CurveEndPoint\" ct=\"  CurveEndPoint  Returns the end point of a curve object.  Syntax  rhinoscriptsyntax.Cur ...\"/><di ky=\"141\" rd=\"modules/curve/curvefilletpoints.htm|CurveFilletPoints\" ct=\"  CurveFilletPoints  Find points at which to cut a pair of curves so that a fillet of a spec ...\"/><di ky=\"142\" rd=\"modules/curve/curveframe.htm|CurveFrame\" ct=\"  CurveFrame  Returns the plane at a parameter of a curve. The plane is based on the tangent ...\"/><di ky=\"143\" rd=\"modules/curve/curveknotcount.htm|CurveKnotCount\" ct=\"  CurveKnotCount  Returns the knot count of a curve object.  Syntax  rhinoscriptsyntax.C ...\"/><di ky=\"144\" rd=\"modules/curve/curveknots.htm|CurveKnots\" ct=\"  CurveKnots  Returns the knots, or knot vector, of a curve object.  Syntax  rhinoscript ...\"/><di ky=\"145\" rd=\"modules/curve/curvelength.htm|CurveLength\" ct=\"  CurveLength  Returns the length of a curve object.  Syntax  rhinoscriptsyntax.CurveLen ...\"/><di ky=\"146\" rd=\"modules/curve/curvemidpoint.htm|CurveMidPoint\" ct=\"  CurveMidPoint  Returns the mid point of a curve object.  Syntax  rhinoscriptsyntax.Cur ...\"/><di ky=\"147\" rd=\"modules/curve/curvenormal.htm|CurveNormal\" ct=\"  CurveNormal  Returns the normal direction of the plane in which a planar curve object lies ...\"/><di ky=\"148\" rd=\"modules/curve/curvenormalizedparameter.htm|CurveNormalizedParameter\" ct=\"  CurveNormalizedParameter  Converts a curve parameter to a normalized curve parameter; one  ...\"/><di ky=\"149\" rd=\"modules/curve/curveparameter.htm|CurveParameter\" ct=\"  CurveParameter  Converts a normalized curve parameter to a curve parameter; one within the ...\"/><di ky=\"150\" rd=\"modules/curve/curveperpframe.htm|CurvePerpFrame\" ct=\"  CurvePerpFrame  Returns the perpendicular plane at a parameter of a curve.  The result is  ...\"/><di ky=\"151\" rd=\"modules/curve/curveplane.htm|CurvePlane\" ct=\"  CurvePlane  Returns the plane in which a planar curve lies. Note, this function works only ...\"/><di ky=\"152\" rd=\"modules/curve/curvepointcount.htm|CurvePointCount\" ct=\"  CurvePointCount  Returns the control points count of a curve object.  Syntax  rhinoscr ...\"/><di ky=\"153\" rd=\"modules/curve/curvepoints.htm|CurvePoints\" ct=\"  CurvePoints  Returns the control points, or control vertices, of a curve object.  If the c ...\"/><di ky=\"154\" rd=\"modules/curve/curveradius.htm|CurveRadius\" ct=\"  CurveRadius  Returns the radius of curvature at a point on a curve.  Syntax  rhinoscri ...\"/><di ky=\"155\" rd=\"modules/curve/curveseam.htm|CurveSeam\" ct=\"  CurveSeam  Adjusts the seam, or start/end, point of a closed curve.  Syntax  rhinoscri ...\"/><di ky=\"156\" rd=\"modules/curve/curvestartpoint.htm|CurveStartPoint\" ct=\"  CurveStartPoint  Returns the start point of a curve object.  Syntax  rhinoscriptsyntax ...\"/><di ky=\"157\" rd=\"modules/curve/curvesurfaceintersection.htm|CurveSurfaceIntersection\" ct=\"  CurveSurfaceIntersection  Calculates the intersection of a curve object with a surface obj ...\"/><di ky=\"158\" rd=\"modules/curve/curvetangent.htm|CurveTangent\" ct=\"  CurveTangent  Returns a 3-D vector that is the tangent to a curve at a parameter.  Synta ...\"/><di ky=\"159\" rd=\"modules/curve/curveweights.htm|CurveWeights\" ct=\"  CurveWeights  Returns a list of weight values that are assigned to the control points of a ...\"/><di ky=\"160\" rd=\"modules/curve/dividecurve.htm|DivideCurve\" ct=\"  DivideCurve  Divides a curve object into a specified number of segments.  Syntax  rhin ...\"/><di ky=\"161\" rd=\"modules/curve/dividecurveequidistant.htm|DivideCurveEquidistant\" ct=\"  DivideCurveEquidistant  Divides a curve such that the linear distance between the points i ...\"/><di ky=\"162\" rd=\"modules/curve/dividecurvelength.htm|DivideCurveLength\" ct=\"  DivideCurveLength  Divides a curve object into segments of a specified length.  Syntax  ...\"/><di ky=\"163\" rd=\"modules/curve/ellipsecenterpoint.htm|EllipseCenterPoint\" ct=\"  EllipseCenterPoint  Returns the center point of an elliptical-shaped curve object.  Synt ...\"/><di ky=\"164\" rd=\"modules/curve/ellipsequadpoints.htm|EllipseQuadPoints\" ct=\"  EllipseQuadPoints  Returns the quadrant points of an elliptical-shaped curve object.  Sy ...\"/><di ky=\"165\" rd=\"modules/curve/evaluatecurve.htm|EvaluateCurve\" ct=\"  EvaluateCurve  Evaluates a curve at a parameter.  Syntax  rhinoscriptsyntax.EvaluateCu ...\"/><di ky=\"166\" rd=\"modules/curve/explodecurves.htm|ExplodeCurves\" ct=\"  ExplodeCurves  Explodes, or un-joins,  one more curve objects.  Polycurves will be explode ...\"/><di ky=\"167\" rd=\"modules/curve/extendcurve.htm|ExtendCurve\" ct=\"  ExtendCurve  Extends a non-closed curve object by a line, arc, or smooth extension until i ...\"/><di ky=\"168\" rd=\"modules/curve/extendcurvelength.htm|ExtendCurveLength\" ct=\"  ExtendCurveLength  Extends a non-closed curve object by a line, arc, or smooth extension f ...\"/><di ky=\"169\" rd=\"modules/curve/extendcurvepoint.htm|ExtendCurvePoint\" ct=\"  ExtendCurvePoint  Extends a non-closed curve object by smooth extension to a point.  Syn ...\"/><di ky=\"170\" rd=\"modules/curve/faircurve.htm|FairCurve\" ct=\"  FairCurve  Fairs a curve object. Fair works best on degree 3 (cubic) curves. Fair attempts ...\"/><di ky=\"171\" rd=\"modules/curve/fitcurve.htm|FitCurve\" ct=\"  FitCurve  Reduces the number of curve control points while maintaining the curve&apos;s same ge ...\"/><di ky=\"172\" rd=\"modules/curve/insertcurveknot.htm|InsertCurveKnot\" ct=\"  InsertCurveKnot  Inserts a knot into a curve object.  Syntax  rhinoscriptsyntax.Insert ...\"/><di ky=\"173\" rd=\"modules/curve/isarc.htm|IsArc\" ct=\"  IsArc  Verifies an object is an arc curve object.  Syntax  rhinoscriptsyntax.IsArc (cu ...\"/><di ky=\"174\" rd=\"modules/curve/iscircle.htm|IsCircle\" ct=\"  IsCircle  Verifies an object is a circle curve object.  Syntax  rhinoscriptsyntax.IsCi ...\"/><di ky=\"175\" rd=\"modules/curve/iscurve.htm|IsCurve\" ct=\"  IsCurve  Verifies an object is a curve object.  Syntax  rhinoscriptsyntax.curve.IsCurv ...\"/><di ky=\"176\" rd=\"modules/curve/iscurveclosable.htm|IsCurveClosable\" ct=\"  IsCurveClosable  Decide if it makes sense to close off the curve by moving  the endpoint t ...\"/><di ky=\"177\" rd=\"modules/curve/iscurveclosed.htm|IsCurveClosed\" ct=\"  IsCurveClosed  Verifies an object is a closed curve object.  Syntax  rhinoscriptsyntax ...\"/></ck>";