gXMLBuffer="<?xml version=\"1.0\" encoding=\"UTF-8\"?><ck><di ky=\"530\" rd=\"modules/object/orientobject.htm|OrientObject\" ct=\"  OrientObject  Orients a single object based on input points.  Syntax  rhinoscriptsynta ...\"/><di ky=\"531\" rd=\"modules/object/rotateobject.htm|RotateObject\" ct=\"  RotateObject  Rotates a single object. Rotation is based on the active construction plane. ...\"/><di ky=\"532\" rd=\"modules/object/rotateobjects.htm|RotateObjects\" ct=\"  RotateObjects  Rotates one or more objects. Rotation is based on the active construction p ...\"/><di ky=\"533\" rd=\"modules/object/scaleobject.htm|ScaleObject\" ct=\"  ScaleObject  Scales a single object. This function can be used to perform uniform or non-u ...\"/><di ky=\"534\" rd=\"modules/object/scaleobjects.htm|ScaleObjects\" ct=\"  ScaleObjects  Scales one or more objects. This function can be used to perform uniform or  ...\"/><di ky=\"535\" rd=\"modules/object/selectobject.htm|SelectObject\" ct=\"  SelectObject  Selects a single object.  Syntax  rhinoscriptsyntax.SelectObject (object ...\"/><di ky=\"536\" rd=\"modules/object/selectobjects.htm|SelectObjects\" ct=\"  SelectObjects  Selects one or more objects.  Syntax  rhinoscriptsyntax.SelectObjects ( ...\"/><di ky=\"537\" rd=\"modules/object/shearobject.htm|ShearObject\" ct=\"  ShearObject  Performs a shear transformation on a single object. Transformation is based o ...\"/><di ky=\"538\" rd=\"modules/object/shearobjects.htm|ShearObjects\" ct=\"  ShearObjects  Performs a shear transformation on one or more objects. Transformation is ba ...\"/><di ky=\"539\" rd=\"modules/object/showobject.htm|ShowObject\" ct=\"  ShowObject  Shows a previously hidden object.  Hidden objects are not visible, cannot be s ...\"/><di ky=\"540\" rd=\"modules/object/showobjects.htm|ShowObjects\" ct=\"  ShowObjects  Shows one or more hidden objects.  Hidden objects are not visible, cannot be  ...\"/><di ky=\"541\" rd=\"modules/object/transformobject.htm|TransformObject\" ct=\"  TransformObject  Moves, scales, or rotates an object given a 4x4 transformation matrix. Th ...\"/><di ky=\"542\" rd=\"modules/object/transformobjects.htm|TransformObjects\" ct=\"  TransformObjects  Moves, scales, or rotates one or more objects given a 4x4 transformation ...\"/><di ky=\"543\" rd=\"modules/object/unlockobject.htm|UnlockObject\" ct=\"  UnlockObject  Unlocks a previously locked object.  Locked object are visible, and they can ...\"/><di ky=\"544\" rd=\"modules/object/unlockobjects.htm|UnlockObjects\" ct=\"  UnlockObjects  Unlocks one or more objects.  Locked object are visible, and they can be sn ...\"/><di ky=\"545\" rd=\"modules/object/unselectobject.htm|UnselectObject\" ct=\"  UnselectObject  Unselects a single selected object.  Syntax  rhinoscriptsyntax.Unselec ...\"/><di ky=\"546\" rd=\"modules/object/unselectobjects.htm|UnselectObjects\" ct=\"  UnselectObjects  Unselects one or more selected objects.  Syntax  rhinoscriptsyntax.Un ...\"/><di ky=\"547\" rd=\"modules/plane/distancetoplane.htm|DistanceToPlane\" ct=\"  DistanceToPlane  Returns the distance from a 3-D point to a plane.  Syntax  rhinoscrip ...\"/><di ky=\"548\" rd=\"modules/plane/evaluateplane.htm|EvaluatePlane\" ct=\"  EvaluatePlane  Evaluates a plane at a U,V parameter.  Syntax  rhinoscriptsyntax.Evalua ...\"/><di ky=\"549\" rd=\"modules/plane/intersectplanes.htm|IntersectPlanes\" ct=\"  IntersectPlanes  Calculates the intersection of three planes.  Syntax  rhinoscriptsynt ...\"/><di ky=\"550\" rd=\"modules/plane/moveplane.htm|MovePlane\" ct=\"  MovePlane  Moves the origin of a plane.  Syntax  rhinoscriptsyntax.MovePlane (plane, o ...\"/><di ky=\"551\" rd=\"modules/plane/plane_module.htm|Plane Module\" ct=\"  Plane Methods  The following methods are available for creating and manipulating lines and ...\"/><di ky=\"552\" rd=\"modules/plane/planeclosestpoint.htm|PlaneClosestPoint\" ct=\"  PlaneClosestPoint  Returns the point on a plane that is closest to a test point.  Syntax ...\"/><di ky=\"553\" rd=\"modules/plane/planecurveintersection.htm|PlaneCurveIntersection\" ct=\"  PlaneCurveIntersection  Intersect an infinite plane and a curve object.  Syntax  rhino ...\"/><di ky=\"554\" rd=\"modules/plane/planeequation.htm|PlaneEquation\" ct=\"  PlaneEquation  Returns the equation of  a plane. The standard equation of a plane with a n ...\"/><di ky=\"555\" rd=\"modules/plane/planefitfrompoints.htm|PlaneFitFromPoints\" ct=\"  PlaneFitFromPoints  Returns a plane that was fit through an array of 3-D points.  Syntax ...\"/><di ky=\"556\" rd=\"modules/plane/planefromframe.htm|PlaneFromFrame\" ct=\"  PlaneFromFrame  Construct a plane from a point, and two vectors in the plane.  Syntax  ...\"/><di ky=\"557\" rd=\"modules/plane/planefromnormal.htm|PlaneFromNormal\" ct=\"  PlaneFromNormal  Creates a plane from an origin point and a normal direction vector.  Sy ...\"/><di ky=\"558\" rd=\"modules/plane/planefrompoints.htm|PlaneFromPoints\" ct=\"  PlaneFromPoints  Creates a plane from three non-colinear points.  Syntax  rhinoscripts ...\"/><di ky=\"559\" rd=\"modules/plane/planeplaneintersection.htm|PlanePlaneIntersection\" ct=\"  PlanePlaneIntersection  Calculates the intersection of two planes.  Syntax  rhinoscrip ...\"/><di ky=\"560\" rd=\"modules/plane/planesphereintersection.htm|PlaneSphereIntersection\" ct=\"  PlaneSphereIntersection  Calculates the intersection of a plane and a sphere.     Syntax ...\"/><di ky=\"561\" rd=\"modules/plane/planetransform.htm|PlaneTransform\" ct=\"  PlaneTransform  Transforms a plane.  Syntax  rhinoscriptsyntax.PlaneTransform (plane,  ...\"/><di ky=\"562\" rd=\"modules/plane/rotateplane.htm|RotatePlane\" ct=\"  RotatePlane  Rotates a plane.  Syntax  rhinoscriptsyntax.RotatePlane (plane, angle_deg ...\"/><di ky=\"563\" rd=\"modules/plane/worldxyplane.htm|WorldXYPlane\" ct=\"  WorldXYPlane  Returns Rhino&apos;s world XY plane. This plane could also be created as follows: ...\"/><di ky=\"564\" rd=\"modules/plane/worldyzplane.htm|WorldYZPlane\" ct=\"  WorldYZPlane  Returns Rhino&apos;s world YZ plane. This plane could also be created as follows: ...\"/><di ky=\"565\" rd=\"modules/plane/worldzxplane.htm|WorldZXPlane\" ct=\"  WorldZXPlane  Returns Rhino&apos;s world ZX plane. This plane could also be created as follows: ...\"/><di ky=\"566\" rd=\"modules/pointvector/isvectorparallelto.htm|IsVectorParallelTo\" ct=\"  IsVectorParallelTo  Compares two vectors to see if they are parallel.  Syntax  rhinosc ...\"/><di ky=\"567\" rd=\"modules/pointvector/isvectorperpendicularto.htm|IsVectorPerpendicularTo\" ct=\"  IsVectorPerpendicularTo  Compares two vectors to see if they are perpendicular.  Syntax ...\"/><di ky=\"568\" rd=\"modules/pointvector/isvectortiny.htm|IsVectorTiny\" ct=\"  IsVectorTiny  Verifies that a vector is very short, or tiny - the x,y,z  elements are less ...\"/><di ky=\"569\" rd=\"modules/pointvector/isvectorzero.htm|IsVectorZero\" ct=\"  IsVectorZero  Verifies that a vector is zero, or tiny - the  x,y,z elements are equal to 0 ...\"/><di ky=\"570\" rd=\"modules/pointvector/pointadd.htm|PointAdd\" ct=\"  PointAdd  Adds a 3-D point or a 3-D vector to a 3-D point.  Syntax  rhinoscriptsyntax. ...\"/><di ky=\"571\" rd=\"modules/pointvector/pointarrayboundingbox.htm|PointArrayBoundingBox\" ct=\"  PointArrayBoundingBox  Returns either a world axis-aligned or a construction plane axis-al ...\"/><di ky=\"572\" rd=\"modules/pointvector/pointarrayclosestpoint.htm|PointArrayClosestPoint\" ct=\"  PointArrayClosestPoint  Finds the point in a list of 3-D points that is closest to a test  ...\"/><di ky=\"573\" rd=\"modules/pointvector/pointarraytransform.htm|PointArrayTransform\" ct=\"  PointArrayTransform  Transforms a list of 3-D points.  Syntax  rhinoscriptsyntax.Point ...\"/><di ky=\"574\" rd=\"modules/pointvector/pointclosestobject.htm|PointClosestObject\" ct=\"  PointClosestObject  Finds the object that is closest to a test point.  Syntax  rhinosc ...\"/><di ky=\"575\" rd=\"modules/pointvector/pointcompare.htm|PointCompare\" ct=\"  PointCompare  Compares two 3-D points.  Syntax  rhinoscriptsyntax.PointCompare (point1 ...\"/><di ky=\"576\" rd=\"modules/pointvector/pointdivide.htm|PointDivide\" ct=\"  PointDivide  Divides a 3-D point by a value  Syntax  rhinoscriptsyntax.PointDivide (po ...\"/><di ky=\"577\" rd=\"modules/pointvector/pointsarecoplanar.htm|PointsAreCoplanar\" ct=\"  PointsAreCoplanar  Verifies that a list of 3-D points are co-planar.  Syntax  rhinoscr ...\"/><di ky=\"578\" rd=\"modules/pointvector/pointscale.htm|PointScale\" ct=\"  PointScale  Scales a 3-D point.  Syntax  rhinoscriptsyntax.PointScale (point, scale)  ...\"/><di ky=\"579\" rd=\"modules/pointvector/pointsubtract.htm|PointSubtract\" ct=\"  PointSubtract  Subtracts a 3-D point or a 3-D vector from a 3-D point.  Syntax  rhinos ...\"/><di ky=\"580\" rd=\"modules/pointvector/pointtransform.htm|PointTransform\" ct=\"  PointTransform  Transforms a 3-D point.  Syntax  rhinoscriptsyntax.PointTransform (poi ...\"/><di ky=\"581\" rd=\"modules/pointvector/pointvector_module.htm|PointVector Module\" ct=\"  Point  &amp; Vector Methods  The following methods are available for creating and manipulating ...\"/><di ky=\"582\" rd=\"modules/pointvector/projectpointtomesh.htm|ProjectPointToMesh\" ct=\"  ProjectPointToMesh  Projects one or more points onto one or more meshes.  Syntax  rhin ...\"/><di ky=\"583\" rd=\"modules/pointvector/projectpointtosurface.htm|ProjectPointToSurface\" ct=\"  ProjectPointToSurface  Projects one or more points onto one or more surfaces or polysurfac ...\"/><di ky=\"584\" rd=\"modules/pointvector/pullpoints.htm|PullPoints\" ct=\"  PullPoints  Pulls an array of points to a surface or mesh object. For more information, se ...\"/><di ky=\"585\" rd=\"modules/pointvector/vectoradd.htm|VectorAdd\" ct=\"  VectorAdd  Adds two 3-D vectors.  Syntax  rhinoscriptsyntax.VectorAdd (vector1, vector ...\"/><di ky=\"586\" rd=\"modules/pointvector/vectorangle.htm|VectorAngle\" ct=\"  VectorAngle  Returns the angle, in degrees, between two 3-D vectors.  Syntax  rhinoscr ...\"/><di ky=\"587\" rd=\"modules/pointvector/vectorcompare.htm|VectorCompare\" ct=\"  VectorCompare  Compares two 3-D vectors.  Syntax  rhinoscriptsyntax.VectorCompare (vec ...\"/></ck>";