<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 11" />
<title>AddCutPlane</title>

 <link rel="StyleSheet" href="../../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../../whmsg.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript" src="../../whver.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whutils.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whproxy.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whlang.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whtopic.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	addTocInfo("Modules\nsurface\naddcutplane");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../../whd_show0.gif","../../whd_show2.gif","../../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../../whd_hide0.gif","../../whd_hide2.gif","../../whd_hide1.gif");
addButton("prev",BTN_IMG,"<<","","","","",0,0,"../../whd_prev0.gif","../../whd_prev2.gif","../../whd_prev1.gif");
addButton("next",BTN_IMG,">>","","","","",0,0,"../../whd_next0.gif","../../whd_next2.gif","../../whd_next1.gif");


	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../../index.html", "", ">", "Home", "../../title.htm");
document.write("<a href=\"../../introduction/rhino_package.htm\">Modules<\/a> > <a href=\"surface_module.htm\">surface<\/a> > addcutplane<\/p>");

}
else
	if (window.gbIE4)
		document.location.reload();
    
onLoadHandler = function()
{
	if (window.setRelStartPage)
	{
    setTimeout("setRelStartPage('../../index.html');", 1)

    setTimeout("UpdateBreadCrumbsMarker();", 1);
    }
} 

if (window.addEventListener){  
	window.addEventListener('load', onLoadHandler, false);   
} else if (window.attachEvent){  
	window.attachEvent('onload', onLoadHandler);  
}

function onSetStartPage()
{
	autoSync(1);
	sendSyncInfo();
	sendAveInfoOut();
}
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<script type="text/javascript" src="../../ehlpdhtm.js" language="JavaScript1.2"></script>

<h1>AddCutPlane</h1>
<p>Adds a planar surface through objects at a designated location. &#160;For more information, see the Rhino help file for the <span style="font-weight: bold;">CutPlane</span> command.</p>
<h3>Syntax</h3>
<p class="Code">rhinoscriptsyntax.AddCutPlane (object_ids, start_point, end_point, normal=None)</p>
<p class="Code">rhinoscript.surface.AddCutPlane (object_ids, start_point, end_point, normal=None)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.679%;" />
<col style="width: 90.321%;" />
<tr style="vertical-align: top; height: 24px;">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">object_ids</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;List. &#160;The identifiers of objects that the cutting planes will pass through.</p>
</td>
</tr>
<tr style="vertical-align: top; height: 24px;">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">start_point</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;List of 3 numbers or Point3d. &#160;The start of the line that defines the cutting plane.</p>
</td>
</tr>
<tr style="vertical-align: top; height: 24px;">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">end_point</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;List of 3 numbers or Point3d. &#160;The end of the line that defines the cutting plane.</p>
</td>
</tr>
<tr style="vertical-align: top; height: 24px;">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">normal</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;A vector that will be contained in the returned planar surface. &#160;In the case of Rhino's <span style="font-weight: bold;">CutPlane</span> command, this is the normal to, or Z axis of, the active view's construction plane. &#160;If omitted, the world Z axis is used.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.522%;" />
<col style="width: 90.478%;" />
<tr style="vertical-align: top;">
<td style="width: 9.522%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Guid</p>
</td>
<td style="width: 90.478%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">The identifier of the new object if successful.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td style="width: 9.522%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">None</p>
</td>
<td style="width: 90.478%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">import rhinoscriptsyntax as rs</p>
<p class="Code" style="margin-left: 12px;">objs = rs.GetObjects("Select objects for cut plane")</p>
<p class="Code" style="margin-left: 12px;">if objs:</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;point0 = rs.GetPoint("Start of cut plane")</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;if point0:</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;point1 = rs.GetPoint("End of cut plane", point0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if point1: rs.AddCutPlane( objs, point0, point1 )</p>
<h3>Also See</h3>
<p><a href="addplanesurface.htm">AddPlaneSurface</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
