<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 11" />
<title>AddArcPtTanPt</title>
<link rel="StyleSheet" href="../../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../../whmsg.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript" src="../../whver.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whutils.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whproxy.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whlang.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2" src="../../whtopic.js" charset="utf-8"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	addTocInfo("Modules\ncurve\naddarcpttanpt");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../../whd_show0.gif","../../whd_show2.gif","../../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../../whd_hide0.gif","../../whd_hide2.gif","../../whd_hide1.gif");
addButton("prev",BTN_IMG,"<<","","","","",0,0,"../../whd_prev0.gif","../../whd_prev2.gif","../../whd_prev1.gif");
addButton("next",BTN_IMG,">>","","","","",0,0,"../../whd_next0.gif","../../whd_next2.gif","../../whd_next1.gif");


	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../../index.html", "", ">", "Home", "../../title.htm");
document.write("<a href=\"../../introduction/rhino_package.htm\">Modules<\/a> > <a href=\"curve_module.htm\">curve<\/a> > addarcpttanpt<\/p>");

}
else
	if (window.gbIE4)
		document.location.reload();
    
onLoadHandler = function()
{
	if (window.setRelStartPage)
	{
    setTimeout("setRelStartPage('../../index.html');", 1)

    setTimeout("UpdateBreadCrumbsMarker();", 1);
    }
} 

if (window.addEventListener){  
	window.addEventListener('load', onLoadHandler, false);   
} else if (window.attachEvent){  
	window.attachEvent('onload', onLoadHandler);  
}

function onSetStartPage()
{
	autoSync(1);
	sendSyncInfo();
	sendAveInfoOut();
}
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<script type="text/javascript" src="../../ehlpdhtm.js" language="JavaScript1.2"></script>

<h1>AddArcPtTanPt</h1>
<p>Adds an arc curve, created from a start point, a start direction, and 
 an end point, to the document.</p>
<h3>Syntax</h3>
<p class="Code">rhinoscriptsyntax.AddArcPtTanPt (start, direction, end)</p>
<p class="Code">rhinoscript.curve.AddArcPtTanPt (start, direction, end)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 8.73%;" />
	<col style="width: 91.27%;" />
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 8.73%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">start</p></td>
		<td style="width: 91.27%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Point3d. The starting point 
		 of the arc.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 8.73%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">direction</p></td>
		<td style="width: 91.27%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Vector3d. The arc direction 
		 at <span style="font-style: italic;"><i>start</i></span>.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 8.73%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">end</p></td>
		<td style="width: 91.27%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Point3d. The ending point 
		 of the arc.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 8.987%;" />
	<col style="width: 91.013%;" />
	<tr style="vertical-align: top;">
		<td style="width: 8.987%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Guid</p></td>
		<td style="width: 91.013%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.987%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">None</p></td>
		<td style="width: 91.013%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">import rhinoscriptsyntax as 
 rs</p>
<p class="Code" style="margin-left: 12px;">pick = rs.GetCurveObject(&quot;Select 
 curve to extend&quot;)</p>
<p class="Code" style="margin-left: 12px;">point = rs.GetPoint(&quot;End 
 of extension&quot;)</p>
<p class="Code" style="margin-left: 12px;">domain = rs.CurveDomain(pick[0])</p>
<p class="Code" style="margin-left: 12px;">if abs(pick[4]-domain[0]) &lt; 
 abs(pick[4]-domain[1]):</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;origin 
 = rs.CurveStartPoint(pick[0])</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;tangent 
 = rs.VectorReverse(rs.CurveTangent(pick[0], domain[0]))</p>
<p class="Code" style="margin-left: 12px;">else:</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;origin 
 = rs.CurveEndPoint(pick[0])</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;tangent 
 = rs.CurveTangent(pick[0], domain[1])</p>
<p class="Code" style="margin-left: 12px;">rs.AddArcPtTanPt(origin, tangent, 
 point)</p>
<h3>Also See</h3>
<p><a href="addarc.htm">AddArc</a></p>
<p><a href="addarc3pt.htm">AddArc3Pt</a></p>
<p><a href="isarc.htm">IsArc</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
